-- these are all queries generated by the RentalsDB python file to initialize
-- and fill our tables with sample data.
CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL, 
    username VARCHAR(500), 
    password VARCHAR(500), 
    fname VARCHAR(100), 
    lname VARCHAR(100), 
    phone VARCHAR(20), 
    email VARCHAR(500), 
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS listings (
    id INT NOT NULL, 
    user_id INT NOT NULL, 
    address VARCHAR(1000), 
    city VARCHAR(300), 
    province VARCHAR(300), 
    rooms INT, 
    bathrooms INT, 
    feet INT, 
    heating INT, 
    water INT, 
    hydro INT, 
    type VARCHAR(300), 
    parking INT, 
    price INT, 
    months INT, 
    comment VARCHAR(2000), 
    PRIMARY KEY (id, user_id), 
    FOREIGN KEY (user_id) REFERENCES users(id));

-- INSERT sample data
INSERT INTO users VALUES ('1', 'test1', 'password1', 'Joe', 'Bad', '5493029283', 'joe@gmail.com');
INSERT INTO users VALUES ('2', 'test2', 'password2', 'Steve', 'Pai', '5190981234', 'steve@yahoo.com');
INSERT INTO users VALUES ('3', 'test3', 'password3', 'Robert', 'Li', '1234567890', 'robert@gmail.com');
INSERT INTO listings VALUES ('0', '0', '422 Hazel Street', 'Waterloo', 'Ontario', '1', '1', '700', '1', '1', '1', 'Apartment', '1', '1800', '4', 'Good place to live');
INSERT INTO listings VALUES ('1', '1', '261 Lester Street', 'Waterloo', 'Ontario', '5', '2', '1100', '1', '1', '1', 'Shared room', '1', '495', '8', 'Best for single students');
INSERT INTO listings VALUES ('2', '1', '275 Larch Street', 'Waterloo', 'Ontario', '1', '1', '750', '1', '1', '1', 'Condo', '0', '2000', '4', 'Short-term lease only!');
INSERT INTO listings VALUES ('3', '1', '520 Parkside Drive', 'Waterloo', 'Ontario', '2', '1', '900', '1', '1', '0', 'Apartment', '1', '1800', '12', 'Long-term lease only!');
INSERT INTO listings VALUES ('4', '2', '250 Albert Street', 'Waterloo', 'Ontario', '1', '1', '695', '0', '0', '0', 'Condo', '0', '1800', '4', 'N/A');
INSERT INTO listings VALUES ('5', '3', '161 University Avenue East', 'Waterloo', 'Ontario', '2', '1', '800', '1', '1', '0', 'Condo', '1', '1905', '8', 'Close to universities');