-- test queries on tables generated by initial_tables.sql file
SELECT * FROM users WHERE username='billy';
SELECT * FROM users WHERE email='billybob@gmail.com';
INSERT INTO users VALUES (25, 'billy', 'bob', 'Billy', 'Bob', '911', 'billybob@gmail.com');
SELECT * FROM users WHERE username='billy1';
SELECT * FROM users WHERE email='billybob@gmail.com';
DELETE FROM listings WHERE user_id IN (SELECT id FROM users WHERE username='test2');
DELETE FROM users WHERE username='test2';

-- insert deleted user and listing back
INSERT INTO users VALUES ('2', 'test2', 'password2', 'Steve', 'Pai', '5190981234', 'steve@yahoo.com');
INSERT INTO listings VALUES ('4', '2', '250 Albert Street', 'Waterloo', 'Ontario', '1', '1', '695', '0', '0', '0', 'Condo', '0', '1800', '4', 'N/A');

SELECT COUNT(*) AS c FROM users WHERE username='test1' OR email='test1';
SELECT COUNT(*) AS c FROM users WHERE password='pass' AND (username='test1' OR email='test1');
SELECT * FROM listings AS l LEFT JOIN (SELECT id, fname, lname, phone, email FROM users) AS u ON l.user_id = u.id LIMIT 20;
SELECT * FROM listings AS l LEFT JOIN (SELECT id, fname, lname, phone, email FROM users) AS u ON l.user_id = u.id WHERE l.user_id = 1 ORDER BY l.id DESC;
SELECT address FROM listings WHERE address='415 Keats Way' AND user_id='1'
SELECT id FROM listings WHERE user_id='1' ORDER BY id DESC
INSERT INTO listings(id, user_id, address) VALUES (22, 1, '415 Keats Way');
SELECT COUNT(*) FROM listings WHERE id=22 AND user_id=1	
UPDATE listings SET address='416 Keats Way' WHERE id=22 AND user_id=1
